### ISSUE TITLE
NullPointerException in SimServicePlugin.onRequestPermissionResult()

### ISSUE THREAD

**Issue by doc-rj** [osamagamal65/sim_service#2]
I'm using version 0.0.6 of this plugin from pub, and I'm also using simple_permissions plugin v0.1.9. Whenever I request permissions through the simple_permissions plugin, this plugin crashes with an NPE. The source here on github seems to be out of date, but here's the stack trace:

E/AndroidRuntime( 1328): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.json.JSONObject.toString()' on a null object reference
E/AndroidRuntime( 1328): 	at com.cloudsoft.simservice.SimServicePlugin.onRequestPermissionsResult(SimServicePlugin.java:305)
E/AndroidRuntime( 1328): 	at io.flutter.app.FlutterPluginRegistry.onRequestPermissionsResult(FlutterPluginRegistry.java:191)
E/AndroidRuntime( 1328): 	at io.flutter.app.FlutterActivityDelegate.onRequestPermissionsResult(FlutterActivityDelegate.java:125)
E/AndroidRuntime( 1328): 	at io.flutter.app.FlutterActivity.onRequestPermissionsResult(FlutterActivity.java:133)
E/AndroidRuntime( 1328): 	at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7429)
E/AndroidRuntime( 1328): 	at android.app.Activity.dispatchActivityResult(Activity.java:7280)
E/AndroidRuntime( 1328): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4264)

**Comment by osamagamal65** [comment]
Do you have a sim card on your phone, and this probably won't work on emulators
